blank_issues_enabled: false
contact_links:
  - name: Gradle Discussion Forums
    url: https://discuss.gradle.org
    about: Please ask and answer questions here.
  - name: Create an issue without template
    url: /issues/new
    about: This option is only available for repository maintainers.
