blank_issues_enabled: false
contact_links:
  - name: Some link
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: Create an issue without template
    url: https://github.com/ov7a/issue-management-test/issues/new
    about: This option available only for repository maintainers
