name: Regression
description: Report a problem about something that used to work
title: ''
labels: ["a:regression", "to-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please use our bug report template to report problems with something that has never worked.  
        Regressions reports are greatly appreciated during our RC phase and before a final release.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Tell us what should happen
      value: ""
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Tell us what happens instead of the expected behavior
      value: ""
    validations:
      required: true    
  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: |
        How has this issue affected you? What are you trying to accomplish?
        Providing context helps us come up with a solution that is most useful in the real world
      value: ""
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Provide a self-contained example project as an attached archive or a Github project.
        You can use [the template](https://github.com/gradle/gradle-issue-reproducer) with a Gradle GitHub action set up to showcase your problem.
        In the rare cases where this is infeasible, we will also accept a detailed set of instructions.
      value: ""
    validations:
      required: true    
  - type: input
    id: gradle-version
    attributes:
      label: Gradle version
      description: What version of Gradle are you running?
    validations:
      required: true  
  - type: input
    id: gradle-version
    attributes:
      label: Gradle version that used to work
      description: What version of Gradle gives proper result for your case?
    validations:
      required: true      
  - type: input
    id: build-scan-url
    attributes:
      label: Build scan URL (optional)
    validations:
      required: false      
  - type: textarea
    id: environment
    attributes:
      label: Your Environment (optional)
      description: |
        Include as many relevant details about the environment you experienced the bug in
      value: ""
    validations:
      required: false