name: Remove triage label

on:
  issues:
    types: closed

jobs:
  remove_triage_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: remove label for closed issue
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ github.event.issue.state_reason == 'not_planned' }}
        with:
          labels: triage

  add_triage_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: add label for issue without labels
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.issue.state_reason == 'completed' && github.event.issue.milestone == null }}
        with:
          labels: triage        