name: Remove triage label

on:
  issues:
    types: closed

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: remove label for closed issue
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ github.event.issue.state_reason == 'not_planned' }}
        with:
          labels: triage