name: Feedback

on:
  issues:
    types:
    - edited
    - reopened
  issue_comment:
    types:
    - created
  pull_request_review_comment:
    types:
      - created
  pull_request_target:
    types:
    - edited
    - synchronize
    - converted_to_draft
    - ready_for_review
    - review_requested

jobs:
  remove_pending_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: remove pending labels for updated item
        #TODO: when two labels are added sequentially, both are removed
        #TODO: when a comment is added and a label is added, the label is removed because of comment update event
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ github.event.createdAt >= github.event.issue.updatedAt }}
        with:
          fail_on_error: false
          labels: |
            pending:reproducer
            pending:feedback
            pending:dco
            pending:design
