name: Feedback

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  feedback:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/issue-management-action@719e37ef2bd9bfb42065115b78f3f94d72642808
        with:
          script: "feedback"
