name: Check issues metadata

on:
  issues:
    types: [ opened, unlabeled, closed ]

jobs:
  check_issue_metadata:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: gradle/issue-management-action/issue-metadata@ov7a/pending-labels
      - uses: gradle/issue-management-action/release-notes@dev
