name: Comment on a closed issue

on:
  issue_comment:
    types: [created]

jobs:
  reconsider_closed_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: gradle/issue-management-action/issue-comment-triage@2bd1d359d3d7573db5a9ef9f9b033f7079e987b3
