name: Check issues metadata

on:
  issues:
    types: [ opened, unlabeled, closed, milestoned, demilestoned ]

jobs:
  check_issue_metadata:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: gradle/issue-management-action/issue-metadata@v2
