name: Comment on a closed issue

on:
  issue_comment:
    types: [created]

jobs:
  reconsider_closed_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: gradle/issue-management-action/issue-comment-triage@a680b22ffc5f4946674b46876e8127b630bae550
