name: Check pulls metadata

on:
  pull_request:
    types: [ closed, unlabeled, milestoned, demilestoned ]

jobs:
  check_pull_metadata:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: gradle/issue-management-action/pull-metadata@v2
