name: 'Close stale PRs'
on:
  schedule:
    # Execute every hour at xx:05 to avoid conflicts with other workflows
    - cron: '5 * * * *'
permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          operations-per-run: 50
          ascending: true
          exempt-all-milestones: true

          # ISSUES (deactivated) ----------------------------------------------
          # This workflow should touch no issues, so times are set to -1
          # (see actions/stale documentation for the behavior)
          days-before-issue-stale: -1
          stale-issue-label: stale
          stale-issue-message: >
            **BUG!** This issue should not be marked stale by the "stale" workflow.
            Please report it to @bt-developer-productivity
          days-before-issue-close: -1
          close-issue-message: >
            **BUG!** This issue should not be closed by the "stale" workflow.
            Please report it to @bt-developer-productivity
          close-issue-reason: not_planned

          # PULL REQUESTS -----------------------------------------------------
          days-before-pr-stale: 2 # FIXME: temorary for test
          exempt-pr-labels: "from:contributor"
          stale-pr-label: stale
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had recent activity.
            Given the limited bandwidth of the team, it will be closed if no further activity occurs.
            If you intend to work on this pull request, please ask the team to reopen the PR or push a new PR.
            Thank you for your contributions.
          days-before-pr-close: 1 # FIXME: temorary for test
          close-pr-message: >
            This pull request has been automatically closed due to inactivity.
            If you are still interested in contributing this, please ensure that
            it is rebased against the latest branch (usually `master`), all review
            comments have been addressed and the build is passing.